Move stdout-to-stderr redirection to command trailing

diff --git a/fix-filename-illegal-chars b/fix-filename-illegal-chars
--- a/fix-filename-illegal-chars
+++ b/fix-filename-illegal-chars
@@ -113,13 +113,13 @@ main() {
   # parse options
   tmp="$(getopt -o "${shortopts}" -l "${longopts}" -n "${script_name}" -s 'bash' -- "$@")"
   # shellcheck disable=SC2181
-  [[ $? -eq 0 ]] || { echo >&2 "Error: getopt parsing error."; return 1; }
+  [[ $? -eq 0 ]] || { echo "Error: getopt parsing error." >&2; return 1; }
   eval set -- "$tmp"
   while true; do
     case "$1" in
       -n|--dry-run) dry_run=1; shift;;
       --) shift; break;;
-      *) echo >&2 "Error: args parsing error, unrecognized option: '$1'."; return 2;;
+      *) echo "Error: args parsing error, unrecognized option: '$1'." >&2; return 2;;
     esac
   done
 
@@ -139,7 +139,7 @@ main() {
     fi
     fix_files "${path}" "${dry_run}"
   else
-    echo >&2 "Error: '${path}' path not found."; return 3
+    echo "Error: '${path}' path not found." >&2; return 3
   fi
 }
 
diff --git a/gentags b/gentags
--- a/gentags
+++ b/gentags
@@ -36,7 +36,7 @@ check_depends() {
 
   for i in "${!req_pkgs[@]}"; do
     if ! hash "$i" &>/dev/null; then
-      echo >&2 "Error: '$i' (${req_pkgs[$i]}) not installed. Aborting."
+      echo "Error: '$i' (${req_pkgs[$i]}) not installed. Aborting." >&2
       exit 1
     fi
   done
diff --git a/get-android-makefile-define-macros-list b/get-android-makefile-define-macros-list
--- a/get-android-makefile-define-macros-list
+++ b/get-android-makefile-define-macros-list
@@ -17,7 +17,7 @@ declare -gr top_file2="build/make/core/envsetup.mk"
 
 check_pwd() {
   if [[ ! -f "${top_file}" && ! -f "${top_file2}" ]]; then
-    echo >&2 "Error: Please cd to Android root and run again."
+    echo "Error: Please cd to Android root and run again." >&2
     return 1
   fi
 }
diff --git a/kernel-devicetree-clone b/kernel-devicetree-clone
--- a/kernel-devicetree-clone
+++ b/kernel-devicetree-clone
@@ -66,7 +66,7 @@ down_search() {
   local sibling_clone_ext_unescaped=""
   local j=""
 
-  [[ -f "${parent}" ]] || (echo >&2 "Error: '${parent}' does not existed!" && return 1)
+  [[ -f "${parent}" ]] || (echo "Error: '${parent}' does not existed!" >&2 && return 1)
 
   parent_name="$(basename "${parent}")"
   parent_dir="$(readlink -f "$(dirname "${parent}")")"
@@ -152,9 +152,9 @@ main() {
   local parent_name=""
   local parent_dir=""
 
-  [[ -f "${parent}" ]] || (echo >&2 "Error: '${parent}' does not existed!" && return 2)
-  [[ "${parent##*.}" =~ ^(dts)$ ]] || (echo >&2 "Error: '${parent}' not a dts file!" && return 3)
-  [[ "${prefix}" =~ ^([a-zA-Z])([a-zA-Z0-9]*)([-])$ ]] || (echo -e >&2 "Error: invalid prefix: \"${prefix}\"\\nE.g., \"projectname-\"" && return 4)
+  [[ -f "${parent}" ]] || (echo "Error: '${parent}' does not existed!" >&2 && return 2)
+  [[ "${parent##*.}" =~ ^(dts)$ ]] || (echo "Error: '${parent}' not a dts file!" >&2 && return 3)
+  [[ "${prefix}" =~ ^([a-zA-Z])([a-zA-Z0-9]*)([-])$ ]] || (echo -e "Error: invalid prefix: \"${prefix}\"\\nE.g., \"projectname-\"" >&2 && return 4)
 
   parent="$(readlink -f "${parent}")"  # relocate myself.
   parent_name="$(basename "${parent}")"
diff --git a/kernel-devicetree-traversal b/kernel-devicetree-traversal
--- a/kernel-devicetree-traversal
+++ b/kernel-devicetree-traversal
@@ -38,7 +38,7 @@ down_search() {
   local -a bindings=()
   local j=""
 
-  [[ -f "${parent}" ]] || (echo >&2 "Error: '${parent}' does not existed!" && return 1)
+  [[ -f "${parent}" ]] || (echo "Error: '${parent}' does not existed!" >&2 && return 1)
 
   parent_name="$(basename "${parent}")"
   parent_dir="$(readlink -f "$(dirname "${parent}")")"
@@ -81,8 +81,8 @@ main() {
   local parent_name=""
   local parent_dir=""
 
-  [[ -f "${parent}" ]] || (echo >&2 "Error: '${parent}' does not existed!" && return 2)
-  [[ "${parent##*.}" =~ ^(dts|dtsi)$ ]] || (echo >&2 "Error: '${parent}' not a dts/dtsi file!" && return 3)
+  [[ -f "${parent}" ]] || (echo "Error: '${parent}' does not existed!" >&2 && return 2)
+  [[ "${parent##*.}" =~ ^(dts|dtsi)$ ]] || (echo "Error: '${parent}' not a dts/dtsi file!" >&2 && return 3)
 
   parent="$(readlink -f "${parent}")"  # relocate myself.
   parent_name="$(basename "${parent}")"
diff --git a/reset-file-permission-mode-bits b/reset-file-permission-mode-bits
--- a/reset-file-permission-mode-bits
+++ b/reset-file-permission-mode-bits
@@ -60,7 +60,7 @@ main() {
       find "${default_root}" -regextype 'posix-egrep' -type f -iregex "^.*\\.($ext_ere)$" -print0 | xargs -0 --no-run-if-empty chmod "${exe_mode}"
       ;;
     *)
-      echo >&2 "Error: unexpected search mode: '${search_mode}'!"
+      echo "Error: unexpected search mode: '${search_mode}'!" >&2
       return 1
       ;;
   esac
